name: Deploy Environment - Cloud Run

on:
  deployment

env:
  GCP_SDK_VERSION: 312.0.0

jobs:
  deploy_details:
    name: Define Deployment Details

    runs-on: ubuntu-20.04

    outputs:
      ghcr_container: ghcr.io/${{ steps.deployment_data.outputs.app_container_image }}:${{ steps.deployment_data.outputs.app_container_version }}
      container_registry: ${{ steps.deployment_data.outputs.container_registry }}
      container_image: ${{ steps.deployment_data.outputs.app_container_image }}
      container_version: ${{ steps.deployment_data.outputs.app_container_version }}

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Extract Deployment Details and Report Deployment in Progress
        id: deployment_data
        uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const scriptPath = require('path').resolve('./.github/workflows/scripts/unpack_deployment_payload.js')
              , deploymentPayload = require(scriptPath);
            ;
            await deploymentPayload(context, core, github).unpackAndStart();


  copy_container:
    name: Copy Container to GCP
    runs-on: ubuntu-20.04

    needs: deploy_details

    outputs:
      gcp_container_name: octodemo-db-bookstore

    env:
      GCR_CONTAINER_IMAGE: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/octodemo-db-bookstore:${{ needs.deploy_details.outputs.container_version }}

    steps:
      - name: Sign in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.OCTODEMOBOT_GHPR_TOKEN }}
          registry: ghcr.io

      - name: Pull GHCR Application Container image
        id: container_publish_app
        run: |
          docker pull ${{ needs.deploy_details.outputs.ghcr_container }}
          docker tag ${{ needs.deploy_details.outputs.ghcr_container }} $GCR_CONTAINER_IMAGE

      - name: Sign in to Google Cloud Platform
        uses: google-github-actions/setup-gcloud@master
        with:
          version: ${{ env.GCP_SDK_VERSION }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_TERRAFORM_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Deploy Container to Google Cloud Container Registry
        id: deploy_to_gcp
        run: |
          gcloud auth configure-docker
          docker push $GCR_CONTAINER_IMAGE


  deploy:
    name: Terraform Deploy
    runs-on: ubuntu-20.04

    needs:
      - deploy_details
      - copy_container

    timeout-minutes: 5

    # Set common Terraform execution environment variables
    env:
      TF_VAR_ENVIRONMENT: ${{ github.event.deployment.environment }}
      TF_VAR_gcp_project: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_container_image: ${{ needs.copy_container.outputs.gcp_container_name }}
      TF_VAR_container_tag: ${{ needs.deploy_details.outputs.container_version }}

      # Directory that contains Terraform HCL to run
      TERRAFORM_WORKING_DIRECTORY: ./terraform/cloud_run

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 0.13.5
          terraform_wrapper: true

      - name: Setup Terragrunt
        uses: peter-murray/terragrunt-github-action@v1.0.0
        with:
          terragrunt_version: 0.25.2

      - name: Sign in to Google Cloud Platform
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: ${{ env.GCP_SDK_VERSION }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_TERRAFORM_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Terraform - init
        working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
        run: terragrunt init

      - name: Terraform - validate
        working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
        run: terragrunt validate

      - name: Terraform - plan
        working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
        run: terragrunt plan

      - name: Terraform - apply
        working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
        run: terragrunt apply -auto-approve

      - name: Get Website URL from Terrafom State
        id: terraform_output
        working-directory: ${{ env.TERRAFORM_WORKING_DIRECTORY }}
        run: terraform output website_url

      - name: Report Success
        uses: octokit/request-action@v1.x
        with:
          route: POST /repos/:owner/:repo/deployments/:deployment_id/statuses
          deployment_id: ${{ github.event.deployment.id }}
          environment: ${{ github.event.deployment.environment }}
          description: "Deployed in ${{ github.event.deployment.environment }}"
          state: "success"
          environment_url: ${{ steps.terraform_output.outputs.stdout }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Report Failure
        if: failure()
        uses: octokit/request-action@v1.x
        with:
          route: POST /repos/:owner/:repo/deployments/:deployment_id/statuses
          deployment_id: ${{ github.event.deployment.id }}
          description: "Deploy failed for ${{ github.event.deployment.environment }}"
          environment: ${{ github.event.deployment.environment }}
          state: "failure"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
